services:
  app:
    build:
      context: .
      args:
        ALLOW_INDEXING: ${ALLOW_INDEXING}
        SITE_URL: ${SITE_URL}
        VITE_CONTACT_FORM_WHATSAPP_NUMBER: ${VITE_CONTACT_FORM_WHATSAPP_NUMBER}
    ports:
      - "${HOST_PORT:-80}:80"
    restart: unless-stopped
